import { useState, useEffect } from "react";
import { Sparkles, Copy, Image, RefreshCw, Loader2, Lightbulb, Wand2, ImagePlus, Eye, Monitor, Smartphone, Mail } from "lucide-react";
import { cn } from "@/lib/utils";
import { CampaignBrief } from "@/types/campaign";
import { supabase } from "@/integrations/supabase/client";
import { toast } from "sonner";

interface Props {
  brief: CampaignBrief;
  onNext: () => void;
  onBack: () => void;
}

interface Variant {
  headline: string;
  short: string;
  long: string;
  description: string;
  reasoning?: string;
  imagePrompt?: string;
}

type PreviewFormat = "feed" | "story" | "email";

const objectiveToAngles: Record<string, string[]> = {
  ROAS: ["Value Proposition", "Urgency", "Social Proof"],
  CAC: ["Value Proposition", "Educational", "Social Proof"],
  Leads: ["Educational", "Urgency", "Trust Building"],
  Conversions: ["Urgency", "Value Proposition", "Social Proof"],
  Retention: ["Loyalty", "Social Proof", "Personalization"],
  Reactivation: ["Win-back", "Urgency", "Value Proposition"],
};

export function CreativeStudio({ brief, onNext, onBack }: Props) {
  const suggestedAngles = objectiveToAngles[brief.objectiveType] || ["Value Proposition", "Urgency", "Social Proof"];

  const [angles, setAngles] = useState(
    suggestedAngles.map((label) => ({
      id: label.toLowerCase().replace(/\s+/g, "-"),
      label,
      variants: [] as Variant[],
    }))
  );
  const [selectedAngle, setSelectedAngle] = useState(angles[0]?.id || "");
  const [generatingImage, setGeneratingImage] = useState<string | null>(null);
  const [generatedImages, setGeneratedImages] = useState<Record<string, string>>({});
  const [generatingCopy, setGeneratingCopy] = useState(false);
  const [hasAutoGenerated, setHasAutoGenerated] = useState(false);
  const [customPrompt, setCustomPrompt] = useState("");
  const [selectedVariantForImage, setSelectedVariantForImage] = useState<number | null>(null);
  const [previewVariant, setPreviewVariant] = useState<number | null>(null);
  const [previewFormat, setPreviewFormat] = useState<PreviewFormat>("feed");

  const [imagePrompts, setImagePrompts] = useState([
    { format: "1:1", channel: "Meta Feed", prompt: `${brief.productCategory || "Product"} lifestyle shot for ${brief.objectiveType || "conversion"} campaign, ${brief.brandTone || "professional"} style, clean background` },
    { format: "4:5", channel: "Instagram", prompt: `Hero ${brief.productCategory || "product"} creative, ${brief.brandTone || "professional"} tone, warm lighting, drives ${brief.objectiveType || "engagement"}` },
    { format: "9:16", channel: "Stories/Reels", prompt: `Dynamic vertical creative for ${brief.productCategory || "e-commerce"}, bold typography, ${brief.brandTone || "professional"} feel, optimized for ${brief.objectiveType || "clicks"}` },
  ]);

  useEffect(() => {
    const newAngles = (objectiveToAngles[brief.objectiveType] || ["Value Proposition", "Urgency", "Social Proof"]).map(label => ({
      id: label.toLowerCase().replace(/\s+/g, "-"),
      label,
      variants: [] as Variant[],
    }));
    setAngles(newAngles);
    setSelectedAngle(newAngles[0]?.id || "");
    setHasAutoGenerated(false);
    setImagePrompts([
      { format: "1:1", channel: "Meta Feed", prompt: `${brief.productCategory || "Product"} lifestyle shot for ${brief.objectiveType || "conversion"} campaign, ${brief.brandTone || "professional"} style, clean background` },
      { format: "4:5", channel: "Instagram", prompt: `Hero ${brief.productCategory || "product"} creative, ${brief.brandTone || "professional"} tone, warm lighting, drives ${brief.objectiveType || "engagement"}` },
      { format: "9:16", channel: "Stories/Reels", prompt: `Dynamic vertical creative for ${brief.productCategory || "e-commerce"}, bold typography, ${brief.brandTone || "professional"} feel, optimized for ${brief.objectiveType || "clicks"}` },
    ]);
  }, [brief.objectiveType, brief.productCategory, brief.brandTone]);

  useEffect(() => {
    if (brief.objectiveType && !hasAutoGenerated && angles[0]?.variants.length === 0) {
      handleGenerateCopy();
      setHasAutoGenerated(true);
    }
  }, [angles, hasAutoGenerated]);

  const currentAngle = angles.find(a => a.id === selectedAngle);

  const handleGenerateImage = async (format: string, prompt: string) => {
    setGeneratingImage(format);
    try {
      const { data, error } = await supabase.functions.invoke("generate-image", {
        body: {
          prompt, format,
          objectiveType: brief.objectiveType || "ROAS",
          productCategory: brief.productCategory || "general e-commerce",
          brandTone: brief.brandTone || "Professional",
          geo: brief.geo.join(", ") || "US",
          brandName: brief.brandName || "",
          occasion: brief.occasion || "",
          targetAudience: brief.targetAudience || "",
          uniqueSellingPoints: brief.uniqueSellingPoints || "",
          callToAction: brief.callToAction || "",
          promotionDetails: brief.promotionDetails || "",
        },
      });
      if (error) throw error;
      if (data?.error) throw new Error(data.error);
      setGeneratedImages(prev => ({ ...prev, [format]: data.imageUrl }));
      toast.success(`${brief.productCategory || "Product"} image generated for ${format}`);
    } catch (e: any) {
      console.error(e);
      toast.error(e.message || "Failed to generate image");
    } finally {
      setGeneratingImage(null);
    }
  };

  const handleGenerateVariantImage = async (variant: Variant, variantIndex: number) => {
    const key = `variant-${variantIndex}`;
    setGeneratingImage(key);
    try {
      const prompt = variant.imagePrompt || `${brief.productCategory || "Product"} creative for "${variant.headline}", ${brief.brandTone || "professional"} style${brief.brandName ? `, ${brief.brandName} brand` : ""}`;
      const { data, error } = await supabase.functions.invoke("generate-image", {
        body: {
          prompt, format: "1:1",
          objectiveType: brief.objectiveType || "ROAS",
          productCategory: brief.productCategory || "general e-commerce",
          brandTone: brief.brandTone || "Professional",
          geo: brief.geo.join(", ") || "US",
          brandName: brief.brandName || "",
          occasion: brief.occasion || "",
          targetAudience: brief.targetAudience || "",
          uniqueSellingPoints: brief.uniqueSellingPoints || "",
          callToAction: brief.callToAction || "",
          promotionDetails: brief.promotionDetails || "",
        },
      });
      if (error) throw error;
      if (data?.error) throw new Error(data.error);
      setGeneratedImages(prev => ({ ...prev, [key]: data.imageUrl }));
      toast.success(`Image generated for "${variant.headline}"`);
    } catch (e: any) {
      console.error(e);
      toast.error(e.message || "Failed to generate image");
    } finally {
      setGeneratingImage(null);
    }
  };

  const handleGenerateCopy = async (prompt?: string) => {
    setGeneratingCopy(true);
    try {
      const currentAngleLabel = angles.find(a => a.id === selectedAngle)?.label || "Value Proposition";
      const { data, error } = await supabase.functions.invoke("generate-copy", {
        body: {
          angle: currentAngleLabel,
          objectiveType: brief.objectiveType || "ROAS",
          targetKPI: brief.targetKPI || brief.objectiveType || "ROAS",
          targetValue: brief.targetValue || "4.0x",
          productCategory: brief.productCategory || "general e-commerce",
          brandTone: brief.brandTone || "Professional",
          geo: brief.geo.join(", ") || "US",
          budgetMin: brief.budgetMin,
          budgetMax: brief.budgetMax,
          timeWindow: brief.timeWindow || "30 days",
          customPrompt: prompt || undefined,
          brandName: brief.brandName || "",
          brandDescription: brief.brandDescription || "",
          occasion: brief.occasion || "",
          targetAudience: brief.targetAudience || "",
          painPoints: brief.painPoints || "",
          uniqueSellingPoints: brief.uniqueSellingPoints || "",
          keyMessages: brief.keyMessages || [],
          callToAction: brief.callToAction || "",
          promotionDetails: brief.promotionDetails || "",
          competitorContext: brief.competitorContext || "",
          seasonality: brief.seasonality || "",
          previousCampaignLearnings: brief.previousCampaignLearnings || "",
        },
      });
      if (error) throw error;
      if (data?.error) throw new Error(data.error);
      if (data?.variants) {
        setAngles(prev => prev.map(a =>
          a.id === selectedAngle ? { ...a, variants: [...a.variants, ...data.variants] } : a
        ));
        toast.success(prompt
          ? `Custom variants created for ${currentAngleLabel}`
          : `Copy generated for ${brief.objectiveType || "ROAS"} · ${currentAngleLabel}`
        );
      }
    } catch (e: any) {
      console.error(e);
      toast.error(e.message || "Failed to generate copy");
    } finally {
      setGeneratingCopy(false);
    }
  };

  const handleRegenerateCopy = async () => {
    // Clear existing variants for the current angle, then regenerate
    setAngles(prev => prev.map(a =>
      a.id === selectedAngle ? { ...a, variants: [] } : a
    ));
    setGeneratingCopy(true);
    try {
      const currentAngleLabel = angles.find(a => a.id === selectedAngle)?.label || "Value Proposition";
      const { data, error } = await supabase.functions.invoke("generate-copy", {
        body: {
          angle: currentAngleLabel,
          objectiveType: brief.objectiveType || "ROAS",
          targetKPI: brief.targetKPI || brief.objectiveType || "ROAS",
          targetValue: brief.targetValue || "4.0x",
          productCategory: brief.productCategory || "general e-commerce",
          brandTone: brief.brandTone || "Professional",
          geo: brief.geo.join(", ") || "US",
          budgetMin: brief.budgetMin,
          budgetMax: brief.budgetMax,
          timeWindow: brief.timeWindow || "30 days",
          brandName: brief.brandName || "",
          brandDescription: brief.brandDescription || "",
          occasion: brief.occasion || "",
          targetAudience: brief.targetAudience || "",
          painPoints: brief.painPoints || "",
          uniqueSellingPoints: brief.uniqueSellingPoints || "",
          keyMessages: brief.keyMessages || [],
          callToAction: brief.callToAction || "",
          promotionDetails: brief.promotionDetails || "",
          competitorContext: brief.competitorContext || "",
          seasonality: brief.seasonality || "",
          previousCampaignLearnings: brief.previousCampaignLearnings || "",
        },
      });
      if (error) throw error;
      if (data?.error) throw new Error(data.error);
      if (data?.variants) {
        setAngles(prev => prev.map(a =>
          a.id === selectedAngle ? { ...a, variants: data.variants } : a
        ));
        toast.success(`Copy regenerated for ${currentAngleLabel}`);
      }
    } catch (e: any) {
      console.error(e);
      toast.error(e.message || "Failed to generate copy");
    } finally {
      setGeneratingCopy(false);
    }
  };

  const handleCustomGenerate = () => {
    if (!customPrompt.trim()) return;
    handleGenerateCopy(customPrompt.trim());
    setCustomPrompt("");
  };

  const handleCopyText = (variant: Variant) => {
    const text = `${variant.headline}\n${variant.short}\n${variant.long}`;
    navigator.clipboard.writeText(text);
    toast.success("Copied to clipboard");
  };

  const handleUseVariantPrompt = (variant: Variant, idx: number) => {
    if (variant.imagePrompt) {
      setImagePrompts(prev => prev.map((p, i) => i === 0 ? { ...p, prompt: variant.imagePrompt! } : p));
      setSelectedVariantForImage(idx);
      toast.success("Image prompt updated from variant — scroll down to generate");
    }
  };

  return (
    <div className="space-y-6">
      {/* Objective context banner */}
      <div className="bg-primary/5 border border-primary/15 rounded-xl p-4 flex items-center justify-between">
        <div>
          <p className="text-[11px] text-muted-foreground font-medium">Creatives optimized for</p>
          <p className="text-sm font-bold text-foreground font-display">
            {brief.brandName || "Brand"} · {brief.objectiveType || "ROAS"} · {brief.brandTone || "Professional"} tone · {brief.productCategory || "All Categories"}
          </p>
          <p className="text-xs text-muted-foreground mt-0.5">
            {brief.occasion && <span>{brief.occasion} · </span>}
            {brief.promotionDetails && <span>Promo: {brief.promotionDetails.slice(0, 40)}... · </span>}
            {brief.geo.join(", ")} · {brief.timeWindow}
          </p>
        </div>
        <div className="flex gap-1.5 flex-wrap justify-end">
          {suggestedAngles.map(a => (
            <span key={a} className="text-[10px] px-2.5 py-1 bg-primary/10 text-primary rounded-full font-semibold">{a}</span>
          ))}
        </div>
      </div>

      {/* Creative Prompt Input */}
      <div className="bg-card border border-border rounded-xl p-5 card-elevated">
        <div className="flex items-center gap-2 mb-3">
          <Wand2 className="h-4 w-4 text-primary" />
          <h2 className="text-sm font-bold text-foreground font-display">Custom Creative Direction</h2>
        </div>
        <p className="text-xs text-muted-foreground mb-3">
          Describe what you want — e.g. "focus on eco-friendly angle", "use humor", "target millennials with FOMO". New variants will be added to the current angle.
        </p>
        <div className="flex gap-2">
          <textarea
            value={customPrompt}
            onChange={(e) => setCustomPrompt(e.target.value)}
            placeholder="e.g., Create variants that emphasize sustainability and eco-conscious buying, use emotional triggers..."
            className="flex-1 bg-background border border-border rounded-xl px-4 py-3 text-sm text-foreground placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-primary/20 focus:border-primary transition-all resize-none h-20"
          />
          <button
            onClick={handleCustomGenerate}
            disabled={generatingCopy || !customPrompt.trim()}
            className="px-5 bg-primary text-primary-foreground rounded-xl text-xs font-semibold hover:opacity-90 transition-all flex items-center gap-1.5 disabled:opacity-50 shadow-sm self-end h-10"
          >
            {generatingCopy ? <Loader2 className="h-3 w-3 animate-spin" /> : <Sparkles className="h-3 w-3" />}
            Generate
          </button>
        </div>
      </div>

      {/* Angle Selection */}
      <div className="bg-card border border-border rounded-xl p-6 card-elevated">
        <div className="flex items-center justify-between mb-5">
          <h2 className="text-base font-bold text-foreground font-display">Creative Angles</h2>
          <button
            onClick={handleRegenerateCopy}
            disabled={generatingCopy}
            className="px-4 py-2 bg-primary text-primary-foreground rounded-xl text-xs font-semibold hover:opacity-90 transition-all flex items-center gap-1.5 disabled:opacity-50 shadow-sm"
          >
            {generatingCopy ? <Loader2 className="h-3 w-3 animate-spin" /> : <RefreshCw className="h-3 w-3" />}
            {generatingCopy ? "Generating..." : "Regenerate Copy"}
          </button>
        </div>
        <div className="flex gap-2 mb-6">
          {angles.map((angle) => (
            <button
              key={angle.id}
              onClick={() => setSelectedAngle(angle.id)}
              className={cn(
                "px-4 py-2 rounded-xl text-xs font-semibold border transition-all",
                selectedAngle === angle.id
                  ? "bg-primary text-primary-foreground border-primary shadow-sm"
                  : "bg-secondary text-secondary-foreground border-border hover:border-primary/30"
              )}
            >
              {angle.label}
              {angle.variants.length > 0 && (
                <span className="ml-1.5 text-[10px] opacity-70">({angle.variants.length})</span>
              )}
            </button>
          ))}
        </div>

        <div className="space-y-4">
          {currentAngle && currentAngle.variants.length > 0 ? (
            currentAngle.variants.map((variant, i) => (
              <div key={i} className="border border-border rounded-xl p-5 bg-secondary/30 hover:bg-secondary/50 transition-colors">
                <div className="flex items-start justify-between mb-3">
                  <span className="text-[10px] font-mono text-muted-foreground uppercase font-semibold">Variant {i + 1}</span>
                  <div className="flex items-center gap-2">
                    <button
                      onClick={() => handleUseVariantPrompt(variant, i)}
                      className="text-xs text-primary flex items-center gap-1 hover:opacity-80 font-medium"
                      title="Use this variant's image prompt"
                    >
                      <ImagePlus className="h-3 w-3" /> Use Prompt
                    </button>
                    <button onClick={() => handleCopyText(variant)} className="text-xs text-primary flex items-center gap-1 hover:opacity-80 font-medium">
                      <Copy className="h-3 w-3" /> Copy
                    </button>
                  </div>
                </div>
                <h3 className="text-lg font-bold text-foreground mb-2 font-display">{variant.headline}</h3>
                <p className="text-sm text-foreground mb-1">{variant.short}</p>
                <p className="text-xs text-muted-foreground mb-3">{variant.long}</p>
                <span className="text-[10px] px-2.5 py-1 bg-secondary rounded-full text-muted-foreground font-medium">{variant.description}</span>

                {/* Reasoning */}
                {variant.reasoning && (
                  <div className="mt-4 bg-primary/5 border border-primary/10 rounded-lg p-3 flex gap-2">
                    <Lightbulb className="h-3.5 w-3.5 text-primary shrink-0 mt-0.5" />
                    <div>
                      <p className="text-[10px] font-semibold text-primary uppercase tracking-wider mb-1">Why this variant</p>
                      <p className="text-xs text-muted-foreground leading-relaxed">{variant.reasoning}</p>
                    </div>
                  </div>
                )}

                {/* Variant-specific image generation */}
                <div className="mt-4 flex items-center gap-3">
                  {generatedImages[`variant-${i}`] ? (
                    <div className="flex items-center gap-3">
                      <img src={generatedImages[`variant-${i}`]} alt={`Variant ${i + 1}`} className="h-16 w-16 rounded-lg object-cover border border-border" />
                      <button
                        onClick={() => handleGenerateVariantImage(variant, i)}
                        disabled={generatingImage === `variant-${i}`}
                        className="text-xs text-primary font-medium hover:opacity-80 flex items-center gap-1"
                      >
                        {generatingImage === `variant-${i}` ? <Loader2 className="h-3 w-3 animate-spin" /> : <RefreshCw className="h-3 w-3" />}
                        Regenerate
                      </button>
                    </div>
                  ) : (
                    <button
                      onClick={() => handleGenerateVariantImage(variant, i)}
                      disabled={generatingImage === `variant-${i}`}
                      className="px-3 py-2 bg-secondary hover:bg-secondary/80 border border-border rounded-xl text-xs font-medium text-foreground flex items-center gap-1.5 transition-all disabled:opacity-50"
                    >
                      {generatingImage === `variant-${i}` ? (
                        <><Loader2 className="h-3 w-3 animate-spin" /> Generating image...</>
                      ) : (
                        <><ImagePlus className="h-3 w-3 text-primary" /> Generate Image for this Variant</>
                      )}
                    </button>
                  )}
                </div>

                {/* Show image prompt if available */}
                {variant.imagePrompt && (
                  <p className="mt-2 text-[10px] text-muted-foreground italic">
                    📸 {variant.imagePrompt}
                  </p>
                )}
              </div>
            ))
          ) : (
            <div className="border border-dashed border-border rounded-xl p-10 flex flex-col items-center gap-2 text-muted-foreground">
              {generatingCopy ? (
                <>
                  <Loader2 className="h-6 w-6 animate-spin text-primary" />
                  <p className="text-xs">Generating {brief.brandTone || "professional"} copy for {brief.productCategory || "e-commerce"}...</p>
                </>
              ) : (
                <>
                  <Sparkles className="h-6 w-6" />
                  <p className="text-xs">Click "Regenerate Copy" or use the custom prompt above to create variants</p>
                </>
              )}
            </div>
          )}
        </div>
      </div>

      {/* Image Generation */}
      <div className="bg-card border border-border rounded-xl p-6 card-elevated">
        <h2 className="text-base font-bold text-foreground mb-1 font-display">Image Generation</h2>
        <p className="text-xs text-muted-foreground mb-5">
          Prompts pre-filled based on {brief.productCategory || "product category"} and {brief.objectiveType || "objective"}.
          {selectedVariantForImage !== null && <span className="text-primary font-medium"> Meta Feed prompt updated from Variant {selectedVariantForImage + 1}.</span>}
        </p>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          {imagePrompts.map((img, idx) => (
            <div key={img.format} className="border border-border rounded-xl p-4 bg-secondary/20 hover:bg-secondary/30 transition-colors">
              <div className="flex items-center justify-between mb-2">
                <span className="text-xs font-mono text-primary font-semibold">{img.format}</span>
                <span className="text-[10px] text-muted-foreground">{img.channel}</span>
              </div>
              <textarea
                value={img.prompt}
                onChange={(e) => setImagePrompts(prev => prev.map((p, i) => i === idx ? { ...p, prompt: e.target.value } : p))}
                className="w-full bg-background border border-border rounded-xl px-3 py-2 text-xs text-foreground mb-3 resize-none h-16 focus:outline-none focus:ring-2 focus:ring-primary/20 focus:border-primary transition-all"
              />
              <div className="aspect-square bg-secondary rounded-xl flex items-center justify-center mb-3 overflow-hidden">
                {generatingImage === img.format ? (
                  <div className="flex flex-col items-center gap-2 text-xs text-primary">
                    <Loader2 className="h-6 w-6 animate-spin" />
                    Creating {brief.productCategory || "product"} visual...
                  </div>
                ) : generatedImages[img.format] ? (
                  <img src={generatedImages[img.format]} alt={`Generated ${img.format}`} className="w-full h-full object-cover" />
                ) : (
                  <Image className="h-8 w-8 text-muted-foreground/30" />
                )}
              </div>
              <button
                onClick={() => handleGenerateImage(img.format, img.prompt)}
                disabled={generatingImage === img.format}
                className="w-full px-3 py-2.5 bg-primary text-primary-foreground rounded-xl text-xs font-semibold hover:opacity-90 transition-all flex items-center justify-center gap-1 disabled:opacity-50 shadow-sm"
              >
                <Sparkles className="h-3 w-3" />
                {generatedImages[img.format] ? "Regenerate" : "Generate Image"}
              </button>
            </div>
          ))}
        </div>
      </div>

      {/* Brand Style Rules */}
      <div className="bg-card border border-border rounded-xl p-6 card-elevated">
        <h2 className="text-base font-bold text-foreground mb-5 font-display">Brand Style Rules</h2>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          <div className="bg-secondary/30 rounded-xl p-4">
            <p className="text-[10px] uppercase tracking-wider text-muted-foreground mb-3 font-semibold">Colors</p>
            <div className="flex gap-2">
              {["#5B4ED8", "#10B981", "#1E293B", "#F8FAFC"].map(c => (
                <div key={c} className="h-7 w-7 rounded-lg border border-border shadow-sm" style={{ backgroundColor: c }} />
              ))}
            </div>
          </div>
          <div className="bg-secondary/30 rounded-xl p-4">
            <p className="text-[10px] uppercase tracking-wider text-muted-foreground mb-3 font-semibold">Do</p>
            <ul className="text-xs text-foreground space-y-1.5">
              <li>✓ Use approved brand colors</li>
              <li>✓ Include CTA in every creative</li>
              <li>✓ Follow accessibility guidelines</li>
            </ul>
          </div>
          <div className="bg-secondary/30 rounded-xl p-4">
            <p className="text-[10px] uppercase tracking-wider text-muted-foreground mb-3 font-semibold">Don't</p>
            <ul className="text-xs text-foreground space-y-1.5">
              <li>✗ Use competitor brand names</li>
              <li>✗ Make unverified claims</li>
              <li>✗ Use all-caps headlines</li>
            </ul>
          </div>
        </div>
      </div>

      {/* Campaign Creative Preview */}
      <div className="bg-card border border-border rounded-xl p-6 card-elevated">
        <div className="flex items-center justify-between mb-5">
          <div className="flex items-center gap-2">
            <Eye className="h-4 w-4 text-primary" />
            <h2 className="text-base font-bold text-foreground font-display">Campaign Preview</h2>
          </div>
          <div className="flex gap-1.5">
            {([
              { id: "feed" as PreviewFormat, label: "Feed Ad", icon: Monitor },
              { id: "story" as PreviewFormat, label: "Story", icon: Smartphone },
              { id: "email" as PreviewFormat, label: "Email", icon: Mail },
            ]).map(f => (
              <button
                key={f.id}
                onClick={() => setPreviewFormat(f.id)}
                className={cn(
                  "px-3 py-1.5 rounded-lg text-[11px] font-semibold flex items-center gap-1.5 transition-all",
                  previewFormat === f.id ? "bg-primary text-primary-foreground" : "bg-secondary text-muted-foreground hover:bg-secondary/80"
                )}
              >
                <f.icon className="h-3 w-3" /> {f.label}
              </button>
            ))}
          </div>
        </div>

        {/* Variant selector */}
        {currentAngle && currentAngle.variants.length > 0 ? (
          <>
            <div className="flex gap-2 mb-5">
              {currentAngle.variants.map((_, i) => (
                <button
                  key={i}
                  onClick={() => setPreviewVariant(i)}
                  className={cn(
                    "px-3 py-1.5 rounded-lg text-[11px] font-semibold transition-all",
                    (previewVariant ?? 0) === i ? "bg-primary/10 text-primary border border-primary/30" : "bg-secondary text-muted-foreground border border-border"
                  )}
                >
                  Variant {i + 1}
                </button>
              ))}
            </div>

            {(() => {
              const v = currentAngle.variants[previewVariant ?? 0];
              if (!v) return null;
              const imgKey = `variant-${previewVariant ?? 0}`;
              const img = generatedImages[imgKey] || generatedImages["1:1"];

              if (previewFormat === "feed") {
                return (
                  <div className="max-w-md mx-auto bg-background border border-border rounded-2xl overflow-hidden shadow-lg">
                    {/* Header */}
                    <div className="flex items-center gap-3 px-4 py-3 border-b border-border">
                      <div className="h-9 w-9 rounded-full bg-primary/20 flex items-center justify-center text-xs font-bold text-primary">
                        {(brief.brandName || "B").charAt(0)}
                      </div>
                      <div>
                        <p className="text-sm font-semibold text-foreground">{brief.brandName || "Brand"}</p>
                        <p className="text-[10px] text-muted-foreground">Sponsored · {brief.geo.join(", ") || "Global"}</p>
                      </div>
                    </div>
                    {/* Copy */}
                    <div className="px-4 py-3">
                      <p className="text-sm text-foreground leading-relaxed">{v.short}</p>
                    </div>
                    {/* Image */}
                    <div className="aspect-square bg-secondary flex items-center justify-center">
                      {img ? (
                        <img src={img} alt="Creative" className="w-full h-full object-cover" />
                      ) : (
                        <div className="text-center text-muted-foreground">
                          <Image className="h-10 w-10 mx-auto mb-2 opacity-30" />
                          <p className="text-[10px]">Generate an image to see preview</p>
                        </div>
                      )}
                    </div>
                    {/* Headline + CTA */}
                    <div className="px-4 py-3 border-t border-border flex items-center justify-between">
                      <div className="min-w-0 flex-1">
                        <p className="text-xs text-muted-foreground truncate">{brief.landingPageUrl || "yoursite.com"}</p>
                        <p className="text-sm font-bold text-foreground truncate">{v.headline}</p>
                        <p className="text-xs text-muted-foreground truncate">{v.description}</p>
                      </div>
                      <button className="px-4 py-2 bg-primary text-primary-foreground rounded-lg text-xs font-semibold shrink-0 ml-3">
                        {brief.callToAction || "Learn More"}
                      </button>
                    </div>
                  </div>
                );
              }

              if (previewFormat === "story") {
                return (
                  <div className="max-w-[280px] mx-auto bg-background border border-border rounded-2xl overflow-hidden shadow-lg" style={{ aspectRatio: "9/16" }}>
                    <div className="relative h-full flex flex-col">
                      {/* Image fills most */}
                      <div className="flex-1 bg-secondary flex items-center justify-center relative">
                        {img ? (
                          <img src={img} alt="Creative" className="w-full h-full object-cover" />
                        ) : (
                          <Image className="h-10 w-10 text-muted-foreground/30" />
                        )}
                        {/* Brand pill */}
                        <div className="absolute top-3 left-3 flex items-center gap-2 bg-background/80 backdrop-blur-sm rounded-full px-3 py-1.5">
                          <div className="h-6 w-6 rounded-full bg-primary/20 flex items-center justify-center text-[10px] font-bold text-primary">
                            {(brief.brandName || "B").charAt(0)}
                          </div>
                          <span className="text-[10px] font-semibold text-foreground">{brief.brandName || "Brand"}</span>
                        </div>
                      </div>
                      {/* Bottom overlay */}
                      <div className="bg-gradient-to-t from-black/80 to-transparent absolute bottom-0 left-0 right-0 px-4 py-5">
                        <p className="text-white text-sm font-bold mb-1">{v.headline}</p>
                        <p className="text-white/80 text-xs mb-3">{v.short}</p>
                        <button className="w-full py-2.5 bg-white text-black rounded-lg text-xs font-bold">
                          {brief.callToAction || "Shop Now"} ↑
                        </button>
                      </div>
                    </div>
                  </div>
                );
              }

              // Email
              return (
                <div className="max-w-lg mx-auto bg-background border border-border rounded-2xl overflow-hidden shadow-lg">
                  {/* Email header */}
                  <div className="bg-secondary/50 px-6 py-4 border-b border-border">
                    <p className="text-[10px] text-muted-foreground">From: {brief.brandName || "Brand"} &lt;hello@{(brief.brandName || "brand").toLowerCase().replace(/\s/g, "")}.com&gt;</p>
                    <p className="text-[10px] text-muted-foreground">Subject: <span className="font-semibold text-foreground">{v.headline}</span></p>
                  </div>
                  {/* Hero image */}
                  <div className="aspect-[2/1] bg-secondary flex items-center justify-center">
                    {img ? (
                      <img src={img} alt="Creative" className="w-full h-full object-cover" />
                    ) : (
                      <Image className="h-10 w-10 text-muted-foreground/30" />
                    )}
                  </div>
                  {/* Body */}
                  <div className="px-6 py-5">
                    <h3 className="text-lg font-bold text-foreground mb-2 font-display">{v.headline}</h3>
                    <p className="text-sm text-foreground mb-2">{v.short}</p>
                    <p className="text-xs text-muted-foreground mb-4 leading-relaxed">{v.long}</p>
                    <button className="px-6 py-3 bg-primary text-primary-foreground rounded-xl text-sm font-semibold">
                      {brief.callToAction || "Shop Now"} →
                    </button>
                  </div>
                  {/* Footer */}
                  <div className="px-6 py-3 border-t border-border bg-secondary/30">
                    <p className="text-[10px] text-muted-foreground text-center">
                      {brief.brandName || "Brand"} · {brief.promotionDetails || "Limited time offer"} · {brief.geo.join(", ") || "Global"}
                    </p>
                  </div>
                </div>
              );
            })()}
          </>
        ) : (
          <div className="border border-dashed border-border rounded-xl p-10 flex flex-col items-center gap-2 text-muted-foreground">
            <Eye className="h-6 w-6 opacity-40" />
            <p className="text-xs">Generate copy variants above to see the campaign preview</p>
          </div>
        )}
      </div>

      <div className="flex justify-between">
        <button onClick={onBack} className="px-6 py-2.5 bg-secondary text-secondary-foreground rounded-xl text-sm font-semibold hover:opacity-90 transition-all">← Back</button>
        <button onClick={onNext} className="px-6 py-2.5 bg-primary text-primary-foreground rounded-xl text-sm font-semibold hover:opacity-90 transition-all shadow-sm">Continue to Channels →</button>
      </div>
    </div>
  );
}
