import { useState, useEffect } from "react";
import { Sparkles, Copy, Image, RefreshCw, Loader2 } from "lucide-react";
import { cn } from "@/lib/utils";
import { CampaignBrief } from "@/types/campaign";
import { supabase } from "@/integrations/supabase/client";
import { toast } from "sonner";

interface Props {
  brief: CampaignBrief;
  onNext: () => void;
  onBack: () => void;
}

interface Variant {
  headline: string;
  short: string;
  long: string;
  description: string;
}

const objectiveToAngles: Record<string, string[]> = {
  ROAS: ["Value Proposition", "Urgency", "Social Proof"],
  CAC: ["Value Proposition", "Educational", "Social Proof"],
  Leads: ["Educational", "Urgency", "Trust Building"],
  Conversions: ["Urgency", "Value Proposition", "Social Proof"],
  Retention: ["Loyalty", "Social Proof", "Personalization"],
  Reactivation: ["Win-back", "Urgency", "Value Proposition"],
};

export function CreativeStudio({ brief, onNext, onBack }: Props) {
  const suggestedAngles = objectiveToAngles[brief.objectiveType] || ["Value Proposition", "Urgency", "Social Proof"];

  const [angles, setAngles] = useState(
    suggestedAngles.map((label) => ({
      id: label.toLowerCase().replace(/\s+/g, "-"),
      label,
      variants: [] as Variant[],
    }))
  );
  const [selectedAngle, setSelectedAngle] = useState(angles[0]?.id || "");
  const [generatingImage, setGeneratingImage] = useState<string | null>(null);
  const [generatedImages, setGeneratedImages] = useState<Record<string, string>>({});
  const [generatingCopy, setGeneratingCopy] = useState(false);
  const [hasAutoGenerated, setHasAutoGenerated] = useState(false);

  const [imagePrompts, setImagePrompts] = useState([
    { format: "1:1", channel: "Meta Feed", prompt: `${brief.productCategory || "Product"} lifestyle shot for ${brief.objectiveType || "conversion"} campaign, ${brief.brandTone || "professional"} style, clean background` },
    { format: "4:5", channel: "Instagram", prompt: `Hero ${brief.productCategory || "product"} creative, ${brief.brandTone || "professional"} tone, warm lighting, drives ${brief.objectiveType || "engagement"}` },
    { format: "9:16", channel: "Stories/Reels", prompt: `Dynamic vertical creative for ${brief.productCategory || "e-commerce"}, bold typography, ${brief.brandTone || "professional"} feel, optimized for ${brief.objectiveType || "clicks"}` },
  ]);

  useEffect(() => {
    const newAngles = (objectiveToAngles[brief.objectiveType] || ["Value Proposition", "Urgency", "Social Proof"]).map(label => ({
      id: label.toLowerCase().replace(/\s+/g, "-"),
      label,
      variants: [] as Variant[],
    }));
    setAngles(newAngles);
    setSelectedAngle(newAngles[0]?.id || "");
    setHasAutoGenerated(false);
    setImagePrompts([
      { format: "1:1", channel: "Meta Feed", prompt: `${brief.productCategory || "Product"} lifestyle shot for ${brief.objectiveType || "conversion"} campaign, ${brief.brandTone || "professional"} style, clean background` },
      { format: "4:5", channel: "Instagram", prompt: `Hero ${brief.productCategory || "product"} creative, ${brief.brandTone || "professional"} tone, warm lighting, drives ${brief.objectiveType || "engagement"}` },
      { format: "9:16", channel: "Stories/Reels", prompt: `Dynamic vertical creative for ${brief.productCategory || "e-commerce"}, bold typography, ${brief.brandTone || "professional"} feel, optimized for ${brief.objectiveType || "clicks"}` },
    ]);
  }, [brief.objectiveType, brief.productCategory, brief.brandTone]);

  useEffect(() => {
    if (brief.objectiveType && !hasAutoGenerated && angles[0]?.variants.length === 0) {
      handleGenerateCopy();
      setHasAutoGenerated(true);
    }
  }, [angles, hasAutoGenerated]);

  const currentAngle = angles.find(a => a.id === selectedAngle);

  const handleGenerateImage = async (format: string, prompt: string) => {
    setGeneratingImage(format);
    try {
      const { data, error } = await supabase.functions.invoke("generate-image", {
        body: { prompt, format, objectiveType: brief.objectiveType || "ROAS", productCategory: brief.productCategory || "general e-commerce", brandTone: brief.brandTone || "Professional", geo: brief.geo.join(", ") || "US" },
      });
      if (error) throw error;
      if (data?.error) throw new Error(data.error);
      setGeneratedImages(prev => ({ ...prev, [format]: data.imageUrl }));
      toast.success(`${brief.productCategory || "Product"} image generated for ${format}`);
    } catch (e: any) {
      console.error(e);
      toast.error(e.message || "Failed to generate image");
    } finally {
      setGeneratingImage(null);
    }
  };

  const handleGenerateCopy = async () => {
    setGeneratingCopy(true);
    try {
      const currentAngleLabel = angles.find(a => a.id === selectedAngle)?.label || "Value Proposition";
      const { data, error } = await supabase.functions.invoke("generate-copy", {
        body: { angle: currentAngleLabel, objectiveType: brief.objectiveType || "ROAS", targetKPI: brief.targetKPI || brief.objectiveType || "ROAS", targetValue: brief.targetValue || "4.0x", productCategory: brief.productCategory || "general e-commerce", brandTone: brief.brandTone || "Professional", geo: brief.geo.join(", ") || "US", budgetMin: brief.budgetMin, budgetMax: brief.budgetMax, timeWindow: brief.timeWindow || "30 days" },
      });
      if (error) throw error;
      if (data?.error) throw new Error(data.error);
      if (data?.variants) {
        setAngles(prev => prev.map(a => a.id === selectedAngle ? { ...a, variants: data.variants } : a));
        toast.success(`Copy generated for ${brief.objectiveType || "ROAS"} · ${currentAngleLabel}`);
      }
    } catch (e: any) {
      console.error(e);
      toast.error(e.message || "Failed to generate copy");
    } finally {
      setGeneratingCopy(false);
    }
  };

  const handleCopyText = (variant: Variant) => {
    const text = `${variant.headline}\n${variant.short}\n${variant.long}`;
    navigator.clipboard.writeText(text);
    toast.success("Copied to clipboard");
  };

  return (
    <div className="space-y-6">
      {/* Objective context banner */}
      <div className="bg-primary/5 border border-primary/15 rounded-xl p-4 flex items-center justify-between">
        <div>
          <p className="text-[11px] text-muted-foreground font-medium">Creatives optimized for</p>
          <p className="text-sm font-bold text-foreground font-display">
            {brief.objectiveType || "ROAS"} · {brief.brandTone || "Professional"} tone · {brief.productCategory || "All Categories"}
          </p>
          <p className="text-xs text-muted-foreground mt-0.5">
            Target: {brief.targetKPI || brief.objectiveType} {brief.targetValue} · {brief.geo.join(", ")} · {brief.timeWindow}
          </p>
        </div>
        <div className="flex gap-1.5 flex-wrap justify-end">
          {suggestedAngles.map(a => (
            <span key={a} className="text-[10px] px-2.5 py-1 bg-primary/10 text-primary rounded-full font-semibold">{a}</span>
          ))}
        </div>
      </div>

      {/* Angle Selection */}
      <div className="bg-card border border-border rounded-xl p-6 card-elevated">
        <div className="flex items-center justify-between mb-5">
          <h2 className="text-base font-bold text-foreground font-display">Creative Angles</h2>
          <button
            onClick={handleGenerateCopy}
            disabled={generatingCopy}
            className="px-4 py-2 bg-primary text-primary-foreground rounded-xl text-xs font-semibold hover:opacity-90 transition-all flex items-center gap-1.5 disabled:opacity-50 shadow-sm"
          >
            {generatingCopy ? <Loader2 className="h-3 w-3 animate-spin" /> : <RefreshCw className="h-3 w-3" />}
            {generatingCopy ? "Generating..." : "Regenerate Copy"}
          </button>
        </div>
        <div className="flex gap-2 mb-6">
          {angles.map((angle) => (
            <button
              key={angle.id}
              onClick={() => setSelectedAngle(angle.id)}
              className={cn(
                "px-4 py-2 rounded-xl text-xs font-semibold border transition-all",
                selectedAngle === angle.id
                  ? "bg-primary text-primary-foreground border-primary shadow-sm"
                  : "bg-secondary text-secondary-foreground border-border hover:border-primary/30"
              )}
            >
              {angle.label}
            </button>
          ))}
        </div>

        <div className="space-y-4">
          {currentAngle && currentAngle.variants.length > 0 ? (
            currentAngle.variants.map((variant, i) => (
              <div key={i} className="border border-border rounded-xl p-5 bg-secondary/30 hover:bg-secondary/50 transition-colors">
                <div className="flex items-start justify-between mb-3">
                  <span className="text-[10px] font-mono text-muted-foreground uppercase font-semibold">Variant {i + 1}</span>
                  <button onClick={() => handleCopyText(variant)} className="text-xs text-primary flex items-center gap-1 hover:opacity-80 font-medium">
                    <Copy className="h-3 w-3" /> Copy
                  </button>
                </div>
                <h3 className="text-lg font-bold text-foreground mb-2 font-display">{variant.headline}</h3>
                <p className="text-sm text-foreground mb-1">{variant.short}</p>
                <p className="text-xs text-muted-foreground mb-3">{variant.long}</p>
                <span className="text-[10px] px-2.5 py-1 bg-secondary rounded-full text-muted-foreground font-medium">{variant.description}</span>
              </div>
            ))
          ) : (
            <div className="border border-dashed border-border rounded-xl p-10 flex flex-col items-center gap-2 text-muted-foreground">
              {generatingCopy ? (
                <>
                  <Loader2 className="h-6 w-6 animate-spin text-primary" />
                  <p className="text-xs">Generating {brief.brandTone || "professional"} copy for {brief.productCategory || "e-commerce"}...</p>
                </>
              ) : (
                <>
                  <Sparkles className="h-6 w-6" />
                  <p className="text-xs">Click "Regenerate Copy" to create variants for this angle</p>
                </>
              )}
            </div>
          )}
        </div>
      </div>

      {/* Image Generation */}
      <div className="bg-card border border-border rounded-xl p-6 card-elevated">
        <h2 className="text-base font-bold text-foreground mb-1 font-display">Image Generation</h2>
        <p className="text-xs text-muted-foreground mb-5">Prompts pre-filled based on {brief.productCategory || "product category"} and {brief.objectiveType || "objective"}</p>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          {imagePrompts.map((img, idx) => (
            <div key={img.format} className="border border-border rounded-xl p-4 bg-secondary/20 hover:bg-secondary/30 transition-colors">
              <div className="flex items-center justify-between mb-2">
                <span className="text-xs font-mono text-primary font-semibold">{img.format}</span>
                <span className="text-[10px] text-muted-foreground">{img.channel}</span>
              </div>
              <textarea
                value={img.prompt}
                onChange={(e) => setImagePrompts(prev => prev.map((p, i) => i === idx ? { ...p, prompt: e.target.value } : p))}
                className="w-full bg-background border border-border rounded-xl px-3 py-2 text-xs text-foreground mb-3 resize-none h-16 focus:outline-none focus:ring-2 focus:ring-primary/20 focus:border-primary transition-all"
              />
              <div className="aspect-square bg-secondary rounded-xl flex items-center justify-center mb-3 overflow-hidden">
                {generatingImage === img.format ? (
                  <div className="flex flex-col items-center gap-2 text-xs text-primary">
                    <Loader2 className="h-6 w-6 animate-spin" />
                    Creating {brief.productCategory || "product"} visual...
                  </div>
                ) : generatedImages[img.format] ? (
                  <img src={generatedImages[img.format]} alt={`Generated ${img.format}`} className="w-full h-full object-cover" />
                ) : (
                  <Image className="h-8 w-8 text-muted-foreground/30" />
                )}
              </div>
              <button
                onClick={() => handleGenerateImage(img.format, img.prompt)}
                disabled={generatingImage === img.format}
                className="w-full px-3 py-2.5 bg-primary text-primary-foreground rounded-xl text-xs font-semibold hover:opacity-90 transition-all flex items-center justify-center gap-1 disabled:opacity-50 shadow-sm"
              >
                <Sparkles className="h-3 w-3" />
                {generatedImages[img.format] ? "Regenerate" : "Generate Image"}
              </button>
            </div>
          ))}
        </div>
      </div>

      {/* Brand Style Rules */}
      <div className="bg-card border border-border rounded-xl p-6 card-elevated">
        <h2 className="text-base font-bold text-foreground mb-5 font-display">Brand Style Rules</h2>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          <div className="bg-secondary/30 rounded-xl p-4">
            <p className="text-[10px] uppercase tracking-wider text-muted-foreground mb-3 font-semibold">Colors</p>
            <div className="flex gap-2">
              {["#5B4ED8", "#10B981", "#1E293B", "#F8FAFC"].map(c => (
                <div key={c} className="h-7 w-7 rounded-lg border border-border shadow-sm" style={{ backgroundColor: c }} />
              ))}
            </div>
          </div>
          <div className="bg-secondary/30 rounded-xl p-4">
            <p className="text-[10px] uppercase tracking-wider text-muted-foreground mb-3 font-semibold">Do</p>
            <ul className="text-xs text-foreground space-y-1.5">
              <li>✓ Use approved brand colors</li>
              <li>✓ Include CTA in every creative</li>
              <li>✓ Follow accessibility guidelines</li>
            </ul>
          </div>
          <div className="bg-secondary/30 rounded-xl p-4">
            <p className="text-[10px] uppercase tracking-wider text-muted-foreground mb-3 font-semibold">Don't</p>
            <ul className="text-xs text-foreground space-y-1.5">
              <li>✗ Use competitor brand names</li>
              <li>✗ Make unverified claims</li>
              <li>✗ Use all-caps headlines</li>
            </ul>
          </div>
        </div>
      </div>

      <div className="flex justify-between">
        <button onClick={onBack} className="px-6 py-2.5 bg-secondary text-secondary-foreground rounded-xl text-sm font-semibold hover:opacity-90 transition-all">← Back</button>
        <button onClick={onNext} className="px-6 py-2.5 bg-primary text-primary-foreground rounded-xl text-sm font-semibold hover:opacity-90 transition-all shadow-sm">Continue to Channels →</button>
      </div>
    </div>
  );
}
